### PR TITLE
Add Reims, France

### PR DESCRIPTION
**Pull request by paulrostorp**

### CODE REVIEW

**Comment by paulrostorp** [comment]
@drewda does this meet the requirements to be merged ?

**Comment by drewda** [comment]
@paulrostorp thanks for your patience. Please simplify your polygons into rectangles. It is fine for the rectangle to cover a somewhat larger extent around a city.

I see you have opened a number of PRs for a number of smaller towns in France. If you need many of these, you may wish to instead just download an extract for all of France and cut the specific towns you need yourself https://download.geofabrik.de/europe/france.html

**Comment by paulrostorp** [comment]
@drewda I've simplified the polygon, and I'll close the other PRs, but Reims is a pretty important/large town in France. Please  let me know if this PR is acceptable

**Comment by drewda** [comment]
@paulrostorp these edits look good. Thanks.

And thanks for considering which cities to propose.

We'll merge this now, and the first extracts should be available within 24 - 48 hours.

**Pull request merged**
